#!/bin/bash

#			       	                  w	
#                w  | |    .  |         w | |  (| | |           |   |
#   __D__|__|>   _ _| |  |__| |__D__|>  __| |   |_|_|  __D__|_|_|___|
#  |   ..	|	               |  	      |           .			
#
#      Begin, in the name of Allah, the Merciful, the Compassionate

